M48
; DRILL file {KiCad (6.0.0)} date Thu Apr 14 19:32:54 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-04-14T19:32:54-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1280
%
G90
G05
T1
X2.9134Y-5.748
X4.9213Y-5.748
T2
X4.0882Y-2.2303
X4.5382Y-2.2303
T0
M30
